CREATE TABLE IF NOT EXISTS raw_message (
    id BIGSERIAL PRIMARY KEY,
    message_id TEXT NOT NULL UNIQUE,
    station_id TEXT NOT NULL,
    station_name TEXT,
    device_id TEXT NOT NULL,
    protocol_type TEXT NOT NULL,
    protocol_version TEXT,
    group_name TEXT NOT NULL,
    message_type TEXT NOT NULL,
    sequence BIGINT NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    payload_json JSONB NOT NULL,
    ingest_status TEXT NOT NULL,
    parse_status TEXT NOT NULL DEFAULT 'pending',
    parse_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (station_id, sequence),
    CHECK (ingest_status IN ('accepted', 'rejected', 'queued', 'parsed')),
    CHECK (parse_status IN ('pending', 'success', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_raw_message_station_collected
ON raw_message(station_id, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_raw_message_station_group_latest_supported
ON raw_message(station_id, group_name, collected_at DESC, sequence DESC)
WHERE protocol_type IN ('green_power', 'green_power_v20260428', 'jtc_smr');

CREATE INDEX IF NOT EXISTS idx_raw_message_parse_status
ON raw_message(parse_status, received_at DESC);

CREATE TABLE IF NOT EXISTS station_runtime_status (
    station_id TEXT PRIMARY KEY,
    station_name TEXT,
    status TEXT NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    last_heartbeat_at TIMESTAMPTZ,
    last_message_id TEXT,
    last_sequence BIGINT,
    last_uplink_ip TEXT,
    backlog_count INTEGER NOT NULL DEFAULT 0,
    parser_lag_seconds INTEGER,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (status IN ('online', 'suspected_offline', 'offline', 'recovered')),
    CHECK (backlog_count >= 0),
    CHECK (parser_lag_seconds IS NULL OR parser_lag_seconds >= 0)
);

CREATE INDEX IF NOT EXISTS idx_station_runtime_status_status_seen
ON station_runtime_status(status, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS telemetry_current (
    station_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    metric_key TEXT NOT NULL,
    metric_value_double DOUBLE PRECISION,
    metric_value_text TEXT,
    unit TEXT,
    quality TEXT NOT NULL DEFAULT 'good',
    collected_at TIMESTAMPTZ NOT NULL,
    source_message_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (station_id, source_type, source_id, metric_key),
    CHECK (metric_value_double IS NOT NULL OR metric_value_text IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_telemetry_current_station_metric
ON telemetry_current(station_id, metric_key);

CREATE TABLE IF NOT EXISTS telemetry_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    station_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    metric_key TEXT NOT NULL,
    metric_value_double DOUBLE PRECISION,
    metric_value_text TEXT,
    unit TEXT,
    quality TEXT NOT NULL DEFAULT 'good',
    collected_at TIMESTAMPTZ NOT NULL,
    source_message_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (metric_value_double IS NOT NULL OR metric_value_text IS NOT NULL),
    PRIMARY KEY (collected_at, id)
) PARTITION BY RANGE (collected_at);

CREATE TABLE IF NOT EXISTS telemetry_history_default
PARTITION OF telemetry_history DEFAULT;

CREATE INDEX IF NOT EXISTS idx_telemetry_history_station_metric_time
ON telemetry_history(station_id, metric_key, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_history_source_time
ON telemetry_history(source_type, source_id, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_history_station_source_metric_time
ON telemetry_history(station_id, source_type, source_id, metric_key, collected_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at_now()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_station_runtime_status_updated_at ON station_runtime_status;
CREATE TRIGGER trg_station_runtime_status_updated_at
BEFORE UPDATE ON station_runtime_status
FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();
